### ISSUE TITLE
Ray Tracing 

### ISSUE THREAD

**Issue by jsaisagar** [isl-org/Open3D#1321]
Dear all,

Is it possible to find all the polygons and their corresponding depths intersected by the given ray in a mesh?

Thanks,

**Comment by griegler** [comment]
Currently, Open3D has no functionality to do that, but it might be possible to add it to the intersection tests.

**Comment by mattj23** [comment]
Is there still interest in this?  I have recently implemented code to do intersection tests between `Eigen::ParameterizedLine<double, 3>` and Open3D's `TriangleMesh`, as well as between the line and `AxisAlignedBoundingBox` using the branchless slab method, which I used to make a bounding volume hierarchy for accelerating ray/mesh intersections.

I would be willing to contribute some or all of this to Open3D with tests in exchange for the review process.

**Comment by griegler** [comment]
@mattj23 sounds great. Intersection tests and BVH would be a great addition.

**Comment by mattj23** [comment]
@griegler since I haven't contributed to this project before, would you be opposed to me submitting this in three separate PRs so that if there are style or structure changes I need to make I can learn and adjust as we go rather than flooding us both with a ton of code that needs to be reworked?  

I have the line/ray intersections with the AABB's ready with documentation and testing which I can submit first, since it adds no new constructs and is basically a handful of methods and tests.

The triangle intersections I'd like to discuss with someone who has architectural insight, as there's a significant performance benefit to pre-calculating some of the values if a triangle is ever going to be checked for an intersection more than once, and that would suggest the creation of a new class or struct to store those values.  I think it would be helpful to have someone guide me on where and how that should go so that I don't create a pull request for something that clashes with the overall design of the library.

The BVH I'm most excited for, but I'd like to spend some time reworking it based on what I learn before submitting.

**Comment by griegler** [comment]
@mattj23 We can discuss architectural details 1:1 on our discord channel if you want.

**Comment by mattj23** [comment]
That would be helpful, what timezone are you in?

**Comment by griegler** [comment]
@mattj23 CEST

**Comment by benjaminum** [comment]
> The triangle intersections I'd like to discuss with someone who has architectural insight, as there's a significant performance benefit to pre-calculating some of the values if a triangle is ever going to be checked for an intersection more than once, and that would suggest the **creation of a new class or struct** to store those values. I think it would be helpful to have someone guide me on where and how that should go so that I don't create a pull request for something that clashes with the overall design of the library.
> 
> The **BVH** I'm most excited for, but I'd like to spend some time reworking it based on what I learn before submitting.

Hi @mattj23, I am also interested in this feature. Do you have a specific use case or application in mind with the new class or data structures? (single ray or batch of rays, inside outside test, etc?)
What do you think of using something like https://www.embree.org/ ?
Sry, for the many questions.

**Comment by mattj23** [comment]
Hi @benjaminum, 
I'm a mechanical engineer and I've been using Open3D for the past year or so for a handful of related applications which are either related to working with 3d mesh data from structured light scanners or doing simulations to guide the design of industrial robotic workcells.

A few weeks ago I ended up implementing triangle intersections using Open3D's `TriangleMesh` in order to check line of sight between points in a scene, as well as test if points were inside specific volumes.  It's not quite a raytracing application in the classical sense, but it ran too slowly to be useful until I put a BVH around it.

I followed this implementation:

http://geomalgorithms.com/a06-_intersect-2.html#intersect3D_RayTriangle()

...and what I noticed is that about half of the calculations for each triangle are unique to the triangle and have nothing to do with the ray being tested.  I also noticed that the second part of the algorithm is simply a test to determine if a point is within the bounds of a triangle, which is also useful when projecting a point onto a set of triangles.

So, to answer your question, my personal applications aren't classical raytracing, but would typically involve ray and segment checks against triangle meshes for measurement, simulating vision, inside/outside.  

From my perspective as a user of Open3D:
1. I think it would be useful to have a general purpose ray/segment/line to triangle intersection algorithm that doesn't require a lot of setup to use, as the occasional quick check on single rays/segments is a common thing to need but most libraries require a lot of setup to accomplish this, since most ray/triangle intersection software and literature are graphics and are highly optimized
2. That being said, most applications involve a large number of rays being tested against a large number of triangles, so I think it would be important to reasonably consider performance during the implementation by avoiding repeated work and making sure that data structures are thread-safe.  
3. I personally favor having simple, un-opinionated constructs that expose the core feature, then providing several opinionated, complex constructs that are meant for more specific, higher performance applications.  Users who's use-case fits into the bounds of an opinionated option can use it, but those who can't aren't forced to re-invent the wheel from nothing. I don't want to have to create an entire `TriangleMesh` and initialize a BVH around it, then prepare a 'batch' containing a single ray in order to check against a single triangle.  It would still be great to have a BVH that could be generated from a `TriangleMesh` and could run ray batches against it, but hopefully the core classes/structs that was built on would be exposed so that I could just check my one triangle against my one ray.

Embree looks great, but looks highly specialized towards graphics raytracing.  My personal feelings are that if I was trying to do a graphics oriented problem I'd probably go deep into one of the highly specialized libraries like Embree or something GPU based.  What I really value about Open3D (and this is just me, other users and the maintainers may feel differently) is that it's a general purpose, relatively efficient 3D toolkit that compiles on a lot of different platforms without too much hassle that I can use as a starting point when I need to create my own tools or do something slightly off the beaten path.

**Comment by benjaminum** [comment]
Thanks for your answer! It gives a good impression of what the goals for this are.

Having a fine-grained set of geometry functions that can be used for ray tracing or other purposes makes a lot of sense (in contrast to a blackbox toolkit).
Another good point that has a lot of value is the support for many platforms. From the PR it seems it will run on all platforms supported by Eigen, that's good.

Looking forward to it!

**Comment by reyanshsolis** [comment]
Ray Casting has been added to Open3D http://www.open3d.org/docs/latest/tutorial/geometry/ray_casting.html.

Feel free to re-open the issue, if any discussion/help is required.
Thanks
