### ISSUE TITLE
Create ScalableTSDFVolume from existing TSDF

### ISSUE THREAD

**Issue by HM102** [isl-org/Open3D#1365]
Is there a way to initialize the TSDFVolume with already existing (NxNxN) TSDF array. After that, apply the integration to the this volume.

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by reyanshsolis** [comment]
Added.
