### ISSUE TITLE
3d reconstruction

### ISSUE THREAD

**Issue by shadowdk3** [isl-org/Open3D#1413]
hi, 
I am going to use open3d + realsense to develop a 3d scanner.
I capture a set of pcd and try to use Multiway registration example to reconstruct 3d image, and the result is the follow. 
![image](https://user-images.githubusercontent.com/38104992/71339628-05700580-258f-11ea-9397-c70169d7a575.png)

![image](https://user-images.githubusercontent.com/38104992/71339641-0f920400-258f-11ea-94e8-55fc3d13fabc.png)

![image](https://user-images.githubusercontent.com/38104992/71339650-16207b80-258f-11ea-8ea9-d5ea32628b3a.png)

My questions are:
1. How can I import the multiway registration result?
2. I found if I remove `pose_graph = o3d.registration.PoseGraph()`, result will has more error, if it possible can I make 3d reconstruct in live?
3. also I would like to check the rotation angle between frame to frame, I use `o3d.odometry.compute_rgbd_odometry`. If I do not misunderstand, R[:3, :3] is the rotation matrix? I would like to convert to angle, what is the Factor of the rotation matrix? RxRyRz? RzRyRx?

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.

**Comment by theNded** [comment]
In Open3D we use pose graphs assuming full observations are known, so online reconstruction at least for point clouds are not possible. You may look at the Dense SLAM module.

You can loop through `pose_graph.nodes` and access their poses. Their relative poses can be computed by `inv(Ti) Tj`. You can convert the rotation to Euler angles according to your convention, because a rotation is an SO(3) element and it is independent of orders.
