### ISSUE TITLE
Error? different definitions for registration 'fitness' in source code and documentation

### ISSUE THREAD

**Issue by kimeguida** [isl-org/Open3D#1459]
Can you please provide the correct definition of what the 'fitness' in registration is? To be consistent with the code implementation.

in the docs:
"property fitness
    The overlapping area (# of inlier correspondences / **# of points in target**). Higher is better."
http://www.open3d.org/docs/release/python_api/open3d.registration.RegistrationResult.html
http://www.open3d.org/docs/release/tutorial/Basic/icp_registration.html

In the code:
"RegistrationResult GetRegistrationResultAndCorrespondences(...)
result.fitness_ = (double)corres_number / (double)**source.points**_.size();
"

**Comment by syncle** [comment]
Good catch. @qianyizh, could you check which one is correct?

**Comment by qianyizh** [comment]
Yes, we should go with implementation. `fitness` is a percentage number.

**Comment by germanros1987** [comment]
Hi! In the Open3D team, we take your question very seriously. In order to provide better assistance to our users, we are implementing new policies. Now general questions should be asked in our forum: https://forum.open3d.org

Github issues will remain in use for bug reports and feature requests.

We are looking forward to answering your question in our forum!

Best regards.
