### ISSUE TITLE
[geometry.TriangleMesh] Transformation issues: Coordinate Frame translates, when applying rotation only

### ISSUE THREAD

**Issue by inecho** [isl-org/Open3D#1645]
**Desciption**
Just by applying a rotation to the coordinate frame `frame`, a systematic translation is applied with `+ [0.02583774 0.02583774 0.02583774]`

```python
import numpy as np
import open3d as o3d
# 
origin = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0,0,0])
# 
frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0,0,0])
frame.rotate([
[1, 0, 0],
[0, -1, 0],
[0, 0, -1]])

print("Center: ",frame.get_center()) # Center:  [0.02583774 0.02583774 0.02583774]
o3d.visualization.draw_geometries([origin, frame])

```
also, if I want to apply translation to the frame, which shall be correctly aligned, why does one need to invert everything? I want to go for a position of [0, 0, 2]. Need to code:

```python
frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0,0,0])
frame.translate( [0, 0, -2])
frame.rotate([
[1, 0, 0],
[0, -1, 0],
[0, 0, -1]], center=False)
```
`frame.getCenter()` will then output `[0,0,2]`

**Expected behavior**

1. If you apply a rotation to an object, you only rotate it and have exactly **no** translation on it!
2. If you apply a translation to an object at `[0, 0, 0]` with `+ [0, 0, 2]`, I expect the result *NOT* to be [0, 0, **-2**]

**Environment (please complete the following information):**
 - OS: Windows 10.0
 - Python version: 3.7
 - Open3D version: 0.9.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by griegler** [comment]
Regarding the first problem: The center of `origin` is also not at `[0,0,0]`, but `[0.02583774 0.02583774 0.02583774]`. Hence, it is the same as `frame` after `rotate`.

Regarding the second problem: `translate` is doing what you expect it should do. If you print the center of frame directly after `translate` (and before `rotate`), then you get the output `[ 0.02583774  0.02583774 -1.97416226]` which is `[0.02583774 0.02583774 0.02583774] + [0,0,-2]`. Note that you use `rotate` afterwards with `center=False` which means that `rotate` does not center the object prior to rotation and hence, moves the center.

**Comment by SamNPowers** [comment]
Follow-up question:
The documentation for create_coordinate_frame says "The coordinate frame will be centered at origin". Why is it, then, that  get_center() then returns some value other than the origin passed in? 

Poking around a little it looks like the new center is a function of the size passed in. Is it the center of the coordinate axes mesh? It also looks like when you rotate it rotates around this new point, instead of the specified origin. This is all very counterintuitive to me as a consumer of the API. When I create coordinate axes at some origin and then rotate them, my expectation is strongly that the rotation will be around the origin I specified, not around some (essentially) arbitrary point. 

Thanks!
