### ISSUE TITLE
Auditwheel can't patch Open3D's wheels because the built shared object gets put in the purelib directory

### ISSUE THREAD

**Issue by safijari** [isl-org/Open3D#1962]
**Describe the bug**
The build procedure for open3d creates a .whl file where the .so file containing all the bindings to the C++ code gets put into the purelib folder (which is only supposed to have pure python files). As such I can't patch this wheel using auditwheel to vendor in some external dependency (in my case that was libosmesa). See screenshot below for more info:

![image](https://user-images.githubusercontent.com/5191844/84692854-61db2e80-aefb-11ea-882d-eadcd01efc92.png)

**To Reproduce**

1. build a wheel
2. install Auditwheel
3. `auditwheel repair <wheel_name>`

**Expected behavior**
The purelib directly should not contained anything other than python files.

**Environment (please complete the following information):**

- Operating system: manylinux2010 container (centos 6)
- Python version: 3.7
- Open3D version: tried 8, 9, and 10
- Compiler version (if built from source): not sure

**Comment by ssheorey** [comment]
Hi @safijari Open3D wheels can be repaired by `auditwheel` as of release `v0.12` after PR #3516. Some things to keep in mind:
- Build from source is recommended. You should build and repair the wheels on the same machine to reduce the chance of library version mismatch. 
- You will need `auditwheel` v4.0.0 or later, since we need PEP600 support with the `manylinux_2_27_x86_64` tag.
- `auditwheel` uses `patchelf`. You will need a recent version from https://github.com/NixOS/patchelf/releases. `v0.9` from Ubuntu 18.04 does not work.

Here is a sample session. First we add the folder containing `patchelf` to `PATH` and folders containing tensorflow and torch shared libraries to `LD_LIBRARY_PATH`. Use `pip show tensorflow torch` to find their locations.
```
$ export PATH=$PATH:~/.local/bin  # patchelf v0.14.3 is here. 
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.pyenv/versions/3.8.8/envs/open3d/lib/python3.8/site-packages/tensorflow:~/.pyenv/versions/3.8.8/envs/open3d/lib/python3.8/site-packages/torch/lib 
$ auditwheel repair --plat manylinux_2_27_x86_64  ~/Downloads/open3d_linux_x86_64_wheels/open3d-0.14.1-cp38-cp38-manylinux2014_x86_64.whl
INFO:auditwheel.main_repair:Repairing open3d-0.14.1-cp38-cp38-manylinux2014_x86_64.whl
INFO:auditwheel.wheeltools:Previous filename tags: manylinux2014_x86_64
INFO:auditwheel.wheeltools:New filename tags: manylinux2014_x86_64, manylinux_2_27_x86_64
INFO:auditwheel.wheeltools:Previous WHEEL info tags: cp38-cp38-manylinux_2_27_x86_64
INFO:auditwheel.wheeltools:No WHEEL info change needed.
INFO:auditwheel.main_repair:
Fixed-up wheel written to <PWD>/wheelhouse/open3d-0.14.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_27_x86_64.whl
```
Install and test:
```
$ ls -hs wheelhouse/
total 1.9G
1.5G open3d-0.14.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_27_x86_64.whl  # repaired wheel with shared libraries
477M open3d-0.14.1-cp38-cp38-manylinux2014_x86_64.whl  # original wheel
$ pip install wheelhouse/open3d-0.14.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_27_x86_64.whl
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing ./wheelhouse/open3d-0.14.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_27_x86_64.whl
...
Installing collected packages: open3d
Successfully installed open3d-0.14.1
$ python -c "import open3d as o3d; print(o3d.__version__)"
0.14.1

```
