### ISSUE TITLE
Open3D version 0.11.2 cannot load obj file with texture while version 0.9.0.0 has no such problem

### ISSUE THREAD

**Issue by kaixin-bai** [isl-org/Open3D#2654]
Code:
```
import open3d as o3d
print(o3d.__version__)
mesh = o3d.io.read_triangle_mesh("./drill.obj")
o3d.visualization.draw_geometries([mesh])
```
Files:
```
drill.obj
drill.obj.mtl
drill_uv.png
```

In Version 0.9.0.0:
![image](https://user-images.githubusercontent.com/38804949/99984986-06687300-2dae-11eb-8306-eb52a1876cc0.png)

In Version 0.11.2:
![image](https://user-images.githubusercontent.com/38804949/99985077-239d4180-2dae-11eb-9172-b0f8f03be835.png)
and got warning:
```
>>> mesh = o3d.io.read_triangle_mesh("./drill.obj")
[Open3D INFO] Skipping non-triangle primitive geometry of type: 2
[Open3D WARNING] Read geometry::Image failed: file extension png  unknown
```

**Comment by hyaguchi947d** [comment]
I found same issue in 0.13.0, and it may be caused by .mtl file.
In texture line, a white space is added after file name, like
`map_Kd texture.png `
I deleted this white space and read file again it works correctly.

I have cross-checked using meshlab and blender, the .mtl file with white space has been loaded with texture correctly.
