### ISSUE TITLE
Crash when I trying to add texture to the mesh for displaying

### ISSUE THREAD

**Issue by Xelawk** [isl-org/Open3D#2823]
**IMPORTANT: Please use the following template to report the bug.**
```python
# where xyz_list: (num_vertices, 3), uv_face: (3 * num_triangles, 2), f_list: (num_triangles, 3)
xyz_list, nxyz_list, uv_list, f_list = parse_mesh_files(group_mesh, group_face)
uv_face = compute_uv_normal(uv_list, f_list)
mesh = o3d.geometry.TriangleMesh()
mesh.vertices = o3d.utility.Vector3dVector(np.array(xyz_list))
mesh.triangles = o3d.utility.Vector3iVector(np.array(f_list))
mesh.triangle_uvs = o3d.utility.Vector2dVector(np.array(uv_face))
texture = o3d_image('data/texture/uv_texture.jpg')
mesh.textures = [texture]
o3d.visualization.draw_geometries([mesh], window_name='Mesh show')
```
**Describe the bug**
Program is crash when I trying to run the code above

**Comment by ssheorey** [comment]
Hi @Xelawk, please fill out the remaining information in the bug report template. We cannot reproduce the issue otherwise. Especially:

**Environment (please complete the following information):**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: (e.g. Python 3.6)
- Open3D version:
- Is this remote workstation?: yes or no
- How did you install Open3D?: (e.g. pip, conda, build from source)
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

Also, can you reproduce this with v0.12?

**Comment by errissa** [comment]
Hi @Xelawk. Also, take a look at issue #2089  It may be related to your issue.
