### ISSUE TITLE
RSBagReader's `save_frames` saves a different number of frames every time!

### ISSUE THREAD

**Issue by kef95** [isl-org/Open3D#3024]
**Describe the bug**
I'm trying to use `RSBagReader` to save RGBD frames from a rosbag file for an L515 camera. Calling `save_frames()` to save color and depth frames always results in a different number of frames being extracted from the .bag file, and never close to the actual number of frames inside the .bag file.

**To Reproduce**

1. Record using the Realsense viewer and save a .bag file.
2. Create a `RSBagReader` object that reads the file and save the frames.

**Expected behavior**
All frames till EOF should be saved from the .bag file

**Screenshots**
![image](https://user-images.githubusercontent.com/22250294/107568490-b7352000-6bef-11eb-9945-0ef7159ae15d.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7.9
- Open3D version: 0.12.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
no

**Comment by ssheorey** [comment]
Hi @kef95, as far as I can tell, this is a limitation of the `librealsense` ROS bag reader SDK. It's designed to supply a stream of frames that must be retrieved regularly at the frame rate, otherwise some frames can get dropped. We tried the following  workarounds, based on `librealsense` support:
1. `set_real_time(false)` : this caused a deadlock after 4 frames on macOS and Linux.
2.  Explicitly `pause()` playback after retrieving every frame to ensure no frames get dropped, but this causes some memory corruption and sometimes a crash in macOS (not observed in Linux). 
https://github.com/IntelRealSense/librealsense/issues/7547#issuecomment-706984376

We finally used a separate `frame_reader` thread to regularly get frames from the `librealsense` backend somewhat independent of what the user may be doing in the main thread and an extra frame buffer independent of the frame buffer in `librealsense`. This gives the same number of frames as long as the system is not heavily loaded, but this cannot be guaranteed.
