### ISSUE TITLE
Offscreen renderer noise

### ISSUE THREAD

**Issue by aweinmann** [isl-org/Open3D#3214]
**Describe the bug**
When rendering with the offscreen renderer (with 0,0,0,0 as background color) the rendering contains noise.

**To Reproduce**
````
import open3d as o3d
import matplotlib.pyplot as plt

render = o3d.visualization.rendering.OffscreenRenderer(512, 512)
render.scene.set_background(np.array([0,0,0,0]))
img = np.asarray(render.render_to_image()) / 255.0

plt.imshow(img*1000)

````
**Expected behavior**
I would expect that the background stays constant zero.

**Screenshots**
![image](https://user-images.githubusercontent.com/2863595/112461214-04182480-8d60-11eb-9b2d-f1bf5fdd7d18.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version: 0.12
- Is this remote workstation?:  no
- How did you install Open3D?: pip

**Comment by prewettg** [comment]
Technically, (0, 0, 0, 0) is 100% transparent black; (0.0, 0.0, 0.0, 1.0) is solid black.  It doesn't matter in this case, though, since the alpha channel isn't recorded (which is essentially blending onto black).

I can reproduce this, and it looks like the noise is coming from Filament: if I print out the values we get in Renderer::RenderToImage(), I get mostly 0 but a lot of 1. (These being uint8_t, so the range is 0 - 255.) I thought that Filament's tone-mapping might be the culprit, but I set that to linear and quality to high in RenderToImage() and it did not change anything. So something more interesting seems to be going on.

**Comment by prewettg** [comment]
I investigated further, it looks like it is Filament's post-processing. Disabling post-processing makes the result all black. However, setting sampling to 1, disabling ambient occlusions, disabling shadows, or even setting color grading to linear results in low-level noise.
