### ISSUE TITLE
Translation result of Global Registration

### ISSUE THREAD

**Issue by JulianWi21** [isl-org/Open3D#3300]
Hello everyone,

I am trying to registrate point clouds that are either rotated or translated or both. The [Global Registration](http://www.open3d.org/docs/release/tutorial/pipelines/global_registration.html) method exactly meets my needs as the registration result is of high quality. However, I am still struggling to fully understand the transformation matrix of the ICP refine registration method. In order to clear things up I have opposed two registration tasks. For both tasks out of a total of 1 000 000 points the correspondence_set size is at a level of  950 000 points, which indicates a good registration result.

In the first task there's a rotation of 90° between both point clouds, but no translation. Here's the pre-registration scene:
<img src="https://user-images.githubusercontent.com/56548020/115117808-aa8ec880-9fa0-11eb-830e-0e0236ed6467.png" width="400" height="300">

Transformation matrix result:

```
result_icp.transformation = [[ 9.99999995e-01  4.30869145e-05  8.64392304e-05  6.82023750e-04]
                             [-8.64404898e-05  2.92282788e-05  9.99999996e-01 -5.97498966e+01]
                             [ 4.30843879e-05 -9.99999999e-01  2.92320032e-05 -1.88041536e-03]
                             [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```

The translation vector of the transformation matrix after the ICP refine registration method is round about (0,-59,0).

In the second task, there's an x-Axis translation, but no rotation. Again pre-registration scene:

<img src="https://user-images.githubusercontent.com/56548020/115117874-eb86dd00-9fa0-11eb-8d52-70687d62c881.png" width="400" height="300">

Transformation matrix result:
```
result_icp.transformation = [[ 9.99999210e-01 -1.07578837e-03 -6.50184124e-04 -1.00281331e+01]
                             [ 1.07594031e-03  9.99999394e-01  2.33379268e-04 -1.50798249e-02]
                             [ 6.49932664e-04 -2.34078643e-04  9.99999761e-01 -5.26857424e-02]
                             [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```
Here, the translation vector is (-10,0,0).

Can anyone tell me how it is possible, that the translation for the task that does only include a rotation happens to be bigger than the one for the task that obviously does have an actual translation? According to my understanding, the task where there's only a rotation shouldn't even have a notable translation. Is this a bug? This is very confusing to me. 

Thanks in advance.

**Comment by chiarapalu** [comment]
Hey Julian did you find out the solution?

**Comment by JulianWi21** [comment]
Hey, yes I found out that my point clouds rotation center was the center of the coordinate system that's shown in my images. So basically one point cloud gets rotated around the x-Axis (red) and thus changes its position too. As a result, open3D seems to move the point cloud to its original position, hence the big translation vector entries. 

A solution is to move the center of the point clouds to the center of the coordinate system. The center of the point cloud can be calculated with get_center(self), or get_axis_aligned_bounding_box(self) and then get_center(self). After that just add or subtract the center's coordinates to each point of the point cloud.

**Comment by chiarapalu** [comment]
Dear Julian, Thanks for your prompt response. I didn't figure out what is happening to me. 
![pic](https://user-images.githubusercontent.com/59933794/116283678-74193080-a78c-11eb-878d-49ae97cca087.PNG)
I hope you can see the figure. the code I use once I get the transformation matrix (result_icp.transformation) is:

#directly apply the transformation matrix to the source 
DirectTransf=copy.deepcopy(source)
DirectTransf.transform(np.asarray(result_icp.transformation))

# decomposing the Rt matrix in order to get angles and translation vector
Rt_matrix=result_icp.transformation
t1 = np.asarray(Rt_matrix[0:3,3])
Rscip=Rot.from_matrix(Rt_matrix[0:3,0:3])      # from scipy.spatial.transform import Rotation as Rot
Euler=Rscip.as_euler('xyz')

manualTransf = copy.deepcopy(source)
manualTransf .rotate(PCmanualRt.get_rotation_matrix_from_xyz(Euler), center=(0,0,0))
manualTransf =PCmanualRt.translate(t1)

The manualTrans is the green point cloud in the figure, the DirectTransf is the pink one. Target is yellow
Do you notice something wrong? Thanks!

**Comment by theNded** [comment]
@chiarapalu you should use global registration prior to ICP in your use case. Plus the resulting matrix is ready for `transform`, there is no need to convert from the Euler angles.
