### ISSUE TITLE
Find transformation for point clouds of different angles

### ISSUE THREAD

**Issue by lleitner-hub** [isl-org/Open3D#3449]
I have 36 point clouds of a rabbit. Each point cloud is a ~10 degrees different to the previous one. The rabbit was turning on its own axis.
How can I transform these point clouds to get a 3D model of the rabbit?

I am currently trying ICP registration or Multiway registration, but I am not sure if it’s the right thing.

Our idea was, that we transform two point clouds each round to get a new point cloud reference.
First step: 10-degree.ply to 0-degree.ply --> transformed_point_cloud.ply
The combination of 0-degree.ply and the transformed_point_cloud.ply would be our new baseline for the next point-cloud (20-degree)

There you have the point clouds
[hasi.zip](https://github.com/intel-isl/Open3D/files/6488253/hasi.zip)

**Comment by reyanshsolis** [comment]
Hi @lleitner-hub, If you want to use ICP for the same, here is an example for a similar task using our new `Tensor MultiScaleICP`. 
In this example, the input is a sequence of Kitti frames, and transformation between each frame (frame to frame transform), is calculated by ICP, therefore getting us the frame to model transform. 

```cpp
 // Reads the pre-fetched and pre-processed pointcloud frames.            
auto source = pointclouds_device_[i].To(device_);            
auto target = pointclouds_device_[i + 1].To(device_);

// Computes the transformation from pcd_[i] to pcd_[i + 1], for            
// `Frame to Frame Odometry`.            
auto result = RegistrationMultiScaleICP(source, target, voxel_sizes_, criterias_, 
                                                   search_radius_, initial_transform, *estimation_);
            
// `cumulative_transform` before update is from `i to 0`.            
// `result.transformation_` is from i to i + 1.            
// so, `cumulative_transform @ (result.transformation_).Inverse`            
// gives `transformation of [i + 1]th frame to 0` [reference or            
// initial] frame. So, pose of the ego-vehicle / sensor            
// till this frame w.r.t. the inital frame, or `global_pose`            
// or `frame to model transform` is given by `cumulative_transform.`            

cumulative_transform = cumulative_transform.Matmul(result.transformation_.T()));
```

Example:
`https://github.com/intel-isl/Open3D/blob/master/examples/cpp/TICPOdometry.cpp`
To run this example, you need to download a kitti sequence using the python script
`https://github.com/intel-isl/Open3D/blob/master/examples/cpp/registration_example_util/download_kitti.py`

When you can't use ICP: When any of the two consecutive frames are not close. But since that is not the case for you, you may use it.

I hope you find this helpful.
Thanks,
Rishabh

**Comment by reyanshsolis** [comment]
Closing this issue, as resolved.
