### ISSUE TITLE
compute_point_cloud_distance

### ISSUE THREAD

**Issue by Mffff666** [isl-org/Open3D#3605]
Is there any method to return the nearest point index from target for each point in source when using the func compute_point_cloud_distance?

**Comment by sanskar107** [comment]
@Mffff666 you can do that with nearest neighbour search
http://www.open3d.org/docs/release/python_api/open3d.geometry.KDTreeFlann.html#open3d.geometry.KDTreeFlann

**Comment by Mffff666** [comment]
But if use kdtree to walk through the point cloud，it will consume too much time in Python.



---Original---
From: "Sanskar ***@***.***&gt;
Date: Fri, Jun 18, 2021 19:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [intel-isl/Open3D] compute_point_cloud_distance (#3605)




 
@Mffff666 you can do that with nearest neighbour search
 http://www.open3d.org/docs/release/python_api/open3d.geometry.KDTreeFlann.html#open3d.geometry.KDTreeFlann

**Comment by agrodet** [comment]
Let's have have a look at the implementation of `ComputePointCloudDistance` below
https://github.com/intel-isl/Open3D/blob/f79b81e41dbfbcd7e42328d53edda5f6dde1ea1b/cpp/open3d/geometry/PointCloud.cpp#L127-L146

We can see that the main part is indeed to call `KDTreeFlann.SearchKNN` with `knn = 1`. This method only returns distances, but I think it is not too complicated to mimic its behavior to return indices.

If you're using the installed Python library, however, I think there is no other choice to write the loop and the call to `search_knn_vector_3d` manually. Something like the following
```
pcd0 = o3d.io.read_point_cloud("first.pcd")
pcd1 = o3d.io.read_point_cloud("second.pcd")
pcd_tree = o3d.geometry.KDTreeFlann(pcd1)
for i in range(5):
    [k, idx, dist] = pcd_tree.search_knn_vector_3d(pcd0.points[i], 1)
    print(f"Closest point to the {i}th point of first Point Cloud is {idx[0]}")
```
```
Closest point to the 0th point of first Point Cloud is 28430
Closest point to the 1th point of first Point Cloud is 20638
Closest point to the 2th point of first Point Cloud is 8892
Closest point to the 3th point of first Point Cloud is 8932
Closest point to the 4th point of first Point Cloud is 25449
```

Then, because you're doing it manually, I think we would need to add Python parallelization, and we should get something reasonable.

For reference, one can have a look at the documentation linked in sanskar107's comment or the [KDTree tutorial](http://www.open3d.org/docs/release/tutorial/geometry/kdtree.html).

**Comment by reyanshsolis** [comment]
This might work for your purpose:
 
http://www.open3d.org/docs/release/tutorial/geometry/distance_queries.html
