### ISSUE TITLE
Can open3d convert a point cloud image into a depth map?

### ISSUE THREAD

**Issue by arkerman** [isl-org/Open3D#3787]
Can the index of each point in the point cloud correspond to the depth map?
Are there any related functions in open3D ？

**Comment by yiyangd** [comment]
Hi, librealsense provides an [api](https://intelrealsense.github.io/librealsense/doxygen/classrs2_1_1frameset.html#ad47bc7437fc5ca4f23d6e5006665024c) to get the distance from the each point of depth_frame to the sensor.

**Comment by kolian1** [comment]
is there a way to create a mapping between the color image and the xyz/ponit of the relevant pixels in point cloud? Something like the inverse open3d.geometry.PointCloud.create_from_rgbd_image(), so that starting with color and depth data, eventually we would have color, depth, point- all same size os original color image?

**Comment by sanskar107** [comment]
@kolian1 are you looking for something like this ?
http://www.open3d.org/docs/latest/python_api/open3d.geometry.RGBDImage.html#open3d.geometry.RGBDImage.create_from_color_and_depth

**Comment by reyanshsolis** [comment]
Moving this discussion to https://github.com/isl-org/Open3D/issues/3800.
