### ISSUE TITLE
A complete tutorial for 3D reconstruction pipeline similar to your blog post?

### ISSUE THREAD

**Issue by AI-ML-Enthusiast** [isl-org/Open3D#3960]
Would you provide a complete tutorial for this blog post especially for 3D reconstruction:

https://www.youtube.com/watch?v=pLCVCH7ypI4

http://www.open3d.org/author/administratorivcl-org/

Thanks in advanced!

**Comment by maohong30** [comment]
Waiting for this too.. 👍

**Comment by theNded** [comment]
A quick notice on why the progress has been slow: I have been fully rewriting the backend such that the underlying sparse voxel grid is fully accessible, indexable, and operable in pure python (instead of a simple pybind), like this example: https://github.com/isl-org/Open3D/blob/wei/new_voxel_grid/examples/python/new_reconstruction_system/integrate_custom.py

I will be wrapping that up with a tutorial.

**Comment by hduonggithub** [comment]
@theNded 

Exited to try out when it is ready. Thanks!

**Comment by theNded** [comment]
The tutorial is now available at http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/index.html. There will be further upgrades once the tensor-based offline system is ready. Please stay tuned. Issue is closed for now, feel free to reopen.
