### ISSUE TITLE
Any possible solutions on degenerate cases of Color Map Optimization?

### ISSUE THREAD

**Issue by DepinYang** [isl-org/Open3D#4047]
Hi @yxlao , Thanks for your recent contributions on the [Color Map Optimization](https://github.com/isl-org/Open3D/tree/master/cpp/open3d/pipelines/color_map) module. They are really helpful for readability.

I am writing to ask about possibly some degenerated cases:

Suppose we have a mesh representing a large flat plane, and want to use this algorithm to optimize a series of image poses viewing at the planar mesh.

E.g.: In the autonomous driving scenario, a reconstructed ground mesh, which is mostly planar with possible curbs at both sides, and we want to use front-facing camera/surround-view cameras to colorize.

Will the algorithm output a globally drifted trajectory? E.g., in the example above, any translational drift parallel to the ground?

And in such a case, is it possible to solve by adding an absolute pose prior to the trajectory? Do you have any other suggestions?

Thanks.

**Comment by theNded** [comment]
I personally don't think it is the ideal use case for colormap optimization, because the assumption of this setup is outside-in viewpoints, with sufficient overlaps between cameras, using an RGB-D sensor, with apparent textures on the target object. The autonomous driving scenario is the opposite in every aspect. 
I would suggest using feature-based pipelines (e.g. ORB SLAM) to optimize the camera poses and then reconstruction if necessary.
