### ISSUE TITLE
Inconsistent normalization factor used for point covariance matrix calculation between Eigen-based and tensor-based implementation

### ISSUE THREAD

**Issue by phylsix** [isl-org/Open3D#4087]
Hi, I noticed a small difference on the normalization factor used for point covariance matrix calculation, between Eigen-based implementation

https://github.com/isl-org/Open3D/blob/ef0755df3e5dafdd6d2db726739e05f8849a7867/cpp/open3d/utility/Eigen.cpp#L325

, and tenor-based implementation:

https://github.com/isl-org/Open3D/blob/ef0755df3e5dafdd6d2db726739e05f8849a7867/cpp/open3d/t/geometry/kernel/PointCloudImpl.h#L208-L211

It does not make a difference for normal estimation, but I feel it's better to be consistent. Please let me know if this was actually desired. Thanks!

**Comment by reyanshsolis** [comment]
Hi @phylsix, 
Yes, the Tensor based Covariance estimation is a two-pass method including Bessel's correction, which is more robust than the Legacy one-pass or book method. As we are moving towards having a complete Tensor based pipeline including multi-device support, we do not intend to change the legacy implementation much, unless it is a bug fix.  

Using `n-1` instead of `n`: [Bessel's Correction](https://en.wikipedia.org/wiki/Bessel%27s_correction) (Ref. Wiki: The reason for the factor `n − 1` rather than `n` is essentially the same as the reason for the same factor appearing in unbiased estimates of sample variances and sample covariances, which relates to the fact that the mean is not known and is replaced by the sample mean).
Another difference is, that Tensor implementation is based on `two-pass` estimation method for covariance which is numerically more robust than the `textbook` method (legacy) generally used for covariance computation.
