### ISSUE TITLE
Pause function:  when play continuous pointcloud data stream

### ISSUE THREAD

**Issue by chenxyyy** [isl-org/Open3D#4301]
Hello！ I want to know if open3d has a pause function when I play a continuous pointcloud  stream

**Comment by yxlao** [comment]
@chenxyyy could you share the code of how you are currently playing the point cloud stream?

**Comment by chenxyyy** [comment]
OK.  Thank you for your reply.

Here is the code I use to play pointcloud stream. My open3d version is 0.13.0

```
import open3d as o3d
import numpy as np

def open3d_show():
    point_cloud = o3d.geometry.PointCloud()
    vis = o3d.visualization.Visualizer()
    vis.create_window(window_name='32line Lidar', width=1080, height=720, left=300, top=150, visible=True)
    vis.add_geometry(point_cloud)

    render_option = vis.get_render_option()
    render_option.point_size = 1
    render_option.background_color = np.asarray([0, 0, 0])  
    to_reset_view_point = True

    for i in range(10000): # Suppose I have 10000 frames of pointcloud data
        points = np.fromfile(str(i).zfill(6) + ".bin", dtype=np.float32, count=-1).reshape((-1, 4))
        
        point_cloud.points = o3d.utility.Vector3dVector(points[:, :3])
        vis.update_geometry(point_cloud)
        if to_reset_view_point:
            vis.reset_view_point(True)
            to_reset_view_point = False
        vis.poll_events()
        vis.update_renderer()

if __name__ == "__main__":
    open3d_show()
```

For example, I want to pause when playing to a specified frame, what should I do to achieve it?

**Comment by yxlao** [comment]
- Since you're using the [non-blocking visualization](http://www.open3d.org/docs/latest/tutorial/visualization/non_blocking_visualization.html) (which is good), the event loop is driven by the python `for` loop. 
  - Therefore, this becomes essentially a Python problem, not an Open3D-specific problem. 
  - One possible solution is to create a separate thread to listen for keyboard events, and pause/resume the loop when certain keys are detected. You may refer to resources like https://stackoverflow.com/q/11242176/1255535 and https://stackoverflow.com/q/13180941/1255535 .
- In case you're using the blocking visualization, you can use open3d's own [callback binding](http://www.open3d.org/docs/latest/tutorial/visualization/customized_visualization.html#callback-functions).
