### ISSUE TITLE
Unable to install on Ubuntu 18.04 4.15.0-162-generic

### ISSUE THREAD

**Issue by prp20** [isl-org/Open3D#4355]
Trying to build the code from source on Ubuntu 18.04 with kernel version 4.15.0-162-generic. 
Below is the error observed:

**make[3]: *** No rule to make target 'librealsense/lib/libfw.a', needed by 'lib/Release/cpu/open3d_torch_ops.so'.  Stop.
CMakeFiles/Makefile2:2688: recipe for target 'cpp/open3d/ml/pytorch/CMakeFiles/open3d_torch_ops.dir/all' failed
make[2]: *** [cpp/open3d/ml/pytorch/CMakeFiles/open3d_torch_ops.dir/all] Error 2
CMakeFiles/Makefile2:3948: recipe for target 'cpp/pybind/CMakeFiles/install-pip-package.dir/rule' failed
make[1]: *** [cpp/pybind/CMakeFiles/install-pip-package.dir/rule] Error 2
Makefile:1119: recipe for target 'install-pip-package' failed
make: *** [install-pip-package] Error 2**

Below are the steps followed to build a python package from source.

1) git clone --recursive https://github.com/intel-isl/Open3D
2) cd Open3D && git submodule update --init --recursive
3) util/install_deps_ubuntu.sh
4) cmake -DOPEN3D_ML_ROOT=<path to ml root> DPYTHON_EXECUTABLE=<path to python executable> ..
_Inside CMakeLists.txt, following options were modified. 
BUILD_LIBREALSENSE=ON, 
USE_SYSTEM_LIBREALSENSE=ON, 
BUILD_PYTORCH_OPS=ON, 
BUNDLE_OPEN3D_ML=ON_
5) make -j install-pip-package

**Environment**
- Operating system: Ubuntu 18.04
- Kernel Version: 4.15.0-162-generic
- Python version: Python 3.7.5
- Is this remote workstation?: yes 
- How did you install Open3D?: build from source
- Compiler version (if built from source): GCC 7.5.0, clang-10
- CUDA Support: No

**Comment by yxlao** [comment]
@prp20 are you inside some proxy or firewall?

**Comment by prp20** [comment]
Yes. Inside a proxy network

**Comment by yxlao** [comment]
@prp20 does it happen to be Intel's proxy?

This issue is not related to Open3D. It is a network issue. RealSense's build system is trying to fetch some content over the network, but it is not able to do so under proxy, so it disabled some of its components automatically.

We ran into this problem inside Intel's company proxy since `intel.com` is listed as "no proxy". This rule is not always true as some of the resources under `intel.com` belong to the internal network, but some belong to the public internet.

My suggestion is to try 1) disabling realsense; 2) play with your proxy rules; 3) try it in an environment with no proxy.

**Comment by yxlao** [comment]
@benjaminum has some experience on that. Does it look like the problem that you have encountered?

**Comment by prp20** [comment]
Thank you @yxlao . Playing with Proxy it solved the issue.
