### ISSUE TITLE
How to get rid of the following warning: "[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set."

### ISSUE THREAD

**Issue by whizbuzzer** [isl-org/Open3D#4617]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I have created a Visualizer using Open3D tools and whenever I minimize the Visualizer window, I get the following warning:

`[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.`

The warning does not interfere with the functioning of the visualizer, but I would still like to have it removed. Could anyone explain what could trigger this warning and how I could get rid of it?

**Comment by errissa** [comment]
I'm speculating that when the window is minimized it triggers a redraw but height and width are 0 because the window was minimized. The proper solution would be to suppress the redraw on minimize rather than removing the warning. The warning may be important in other cases.

We are no longer updating the legacy visualizer. If you would like to submit a PR to address this issue we would be happy to consider it.
