### ISSUE TITLE
Request to set gradient backgroud in Open3D visualizer

### ISSUE THREAD

**Issue by jun-sh** [isl-org/Open3D#4635]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

![捕获](https://user-images.githubusercontent.com/37541158/150480305-a3832db0-b1c1-49d7-b954-11682f6c936b.PNG)
![捕获2](https://user-images.githubusercontent.com/37541158/150480611-3023e3af-cf76-4283-92d7-e101269ba93a.PNG)

By modify  VisualizerRender.cpp in source code, and rebuild to lib file, I can change backgroud to single color, for example, by changing "glClearColor((GLclampf)background_color(0), (GLclampf)background_color(1),
                 (GLclampf)background_color(2), 1.0f);"
to "glClearColor((GLclampf)background_color(1), (GLclampf)background_color(0),
                 (GLclampf)background_color(0), 1.0f);"
I will get red backgroud.

The problem is, if I copy the code, which created gradient backgroud in another opengl program, the result got is just all black backgroud, and nothing else changes.
![捕获3](https://user-images.githubusercontent.com/37541158/150480927-86f72f4c-ba2f-4a62-9878-93434eb39a3c.PNG)
 
Added code list here:
    // Gradient background color
    glClear(GL_COLOR_BUFFER_BIT);
    glClear(GL_DEPTH_BUFFER_BIT);
    glBegin(GL_POLYGON);
    glColor3f(254.f / 255, 254.f / 255, 254.f / 255);
    glVertex3f(-1.0, -1.0, 0);
    glColor3f(200.f / 255, 206.f / 255, 221.f / 255);
    glVertex3f(-1.0, 1.0, 0);
    glColor3f(200.f / 255, 206.f / 255, 221.f / 255);
    glVertex3f(1.0, 1.0, 0);
    glColor3f(254.f / 255, 254.f / 255, 254.f / 255);
    glVertex3f(1.0, -1.0, 0);
    glEnd();
    glFlush();

Environment: Win10, Open3D 0.10.0, VS2019
 
Thanks in advance!

**Comment by errissa** [comment]
At the point at which you trying to render the quad to create the gradient the view and projection matrices are set for rendering a model. What you are trying to do is a render a full screen quad using NDC. The easiest thing to do would be to setup an orthographic projection and match the quad to the extents of that projection.

You might consider moving to the new visualizer. It doesn't support gradient backgrounds but it does support skyboxes and it's relatively easy to author a skybox with your desired gradient. For example, see the default skybox:
<img width="1392" alt="Screen Shot 2022-01-21 at 9 04 28 AM" src="https://user-images.githubusercontent.com/3722407/150540380-1bddb071-01df-4cc3-ba9e-be8d46f80672.png">

Since the legacy visualizer will be soon be deprecated and we are not add features to it, I am closing this issue. However, if you are able to get the gradient to work and want to contribute the feature we would welcome a PR.

**Comment by jun-sh** [comment]
Thanks a lot! I will give it a try.
