### ISSUE TITLE
Is it possible to compute non-normalized normal vector field across the point cloud?

### ISSUE THREAD

**Issue by antelk** [isl-org/Open3D#5213]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Is it possible to obtain normals that are not unit, i.e, non-normalized normals across the surface?

Minimal working example:
```python
import numpy as np
import open3d as o3d

ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

pcd.estimate_normals()
n = np.asarray(pcd.normals)

pcd_unit = pcd.normalize_normals()
n_unit = np.asarray(pcd_unit.normals)
```

While `n` and `n_unit` should not contain the same values, they do:
```python
In [1]: (n == n_unit).all()
Out[1]: True
```

I guess that underlying code approximates normal distribution as described in [Hoppe et al. 1992](https://sites.stat.washington.edu/wxs/Siggraph-92/siggraph92.pdf) so normals should be "unit" by default, but then why the method `normalize_normals` even exists?

Thank you!

**Comment by yuecideng** [comment]
The legacy version of open3d `estimate_normals` method use Eigen `SelfAdjointEigenSolver` as backend to compute the eigenvector as noramls, which will be normalized inside eigen. The normals of `PointCloud` geometry can be also assigned externally like this:
```python
# ext_normals is numpy (n x 3) ndarray
pcd.normals = o3d.utility.Vector3dVector(ext_normals)
```
where the `ext_normals` provided by user can be non-normalized. So in that situation  `normalize_normals` make sense for user.

One more thing interesting is that, the code in your example will also return `True`. The reason is that the `n = np.asarray(pcd.normals)` will not copy the memory of normal data, and  `estiamte_normals` will return `pcd` itself (also no copy). Therefore, the variable `n` and `n_unit` are exactly the same thing...
if you try 
```python
pcd.estimate_normals()
n = np.array(pcd.normals) # or n = np.asarray(pcd.normals).copy()

pcd_unit = pcd.normalize_normals()
n_unit = np.asarray(pcd_unit.normals)
```
Now they are two different variables and you will get `False` ouput, but it is mainly due to the numerical precision.

**Comment by antelk** [comment]
Thank you. This is extremely helpful!
Is there any alternative in finding normals that are not normalized within open3d?

**Comment by yuecideng** [comment]
To my knowledge, there is no methods in `open3d` that can satisfy your request. Maybe you can find them from other libraries.
