### ISSUE TITLE
is there any advantage of colored ICP over robust ICP for colored point clouds?

### ISSUE THREAD

**Issue by juandavid212** [isl-org/Open3D#5362]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello,
I'm currently working with colored point clouds of objects without a background, the point clouds are obtained from an RGB-D camera.
After some post-processing, the cloud is quite clean and dense.
The point clouds are normally misaligned by a few centimeters, after some trials the ICP with a robust kernel (similar to the examples) is more likely to find a solution than the colored ICP.
Is this normal? I thought that colored ICP is the best solution for colored point clouds.

**Comment by hernot** [comment]
Even without robust kernel standard point to plane ICP can yield better results than coloured ICP. 
I guess it depends on the size of your objects and whether the point data is in meter, cm or millimeter units. Colours are allways  normalized to [0,1]. Consequently if your point data is in meter and your objects are less than 1m in size the color information becomes dominant in search for corresponding points (assumeing KDTree). in other words if your point colors do not expose color patterns with sharp edges like in the tutorial the color information likely distracts the point to plane algorithm from the true position than facilitating finding the proper one.

Therefore we stayed with standard point-to-plane and instead of considering color information do a second run where we swap source and target and use the inverted the transformation matrix resulting from the first run to achieve sort of Symmetric icp

**Comment by juandavid212** [comment]
Thanks for your answer.
Regarding the "Symmetric ICP", what's the benefit of swapping the source and target point clouds and using the inverted result (of the first run) as an initial guest?
This is similar to running ICP only once with twice the iterations, right?

**Comment by hernot** [comment]
No: Point to plane consideres the surface normals of the target point cloud and tries to optimize 

```
E(T) = sum_{(p,q) in K } ( ( p - T q) * n_p)^2

T ... resulting Transformatoin
p ... Target points
q ... source points 
n_p ... surface normals of target
K ... correspondence set
```
thus when swapping source and target the following is optimized 


```
E(T) = sum_{(q,p) in K } ( ( q - T p) * n_q)^2

T ... resulting Transformatoin
p ... Target points
q ... source points 
n_p ... surface normals of target
K ... correspondence set
```

In other words in the firt run the transformation is optimized that points of source fit best onto the surface of target. The second adjust the transformation that also the target points fit optimally to the surface of source. This is important in cases where source and target contain multiple similar surface patches with diverging orientation. In that case it can be that forward fitting would align the wrong structural pairs with the efect that the distance between target surface and source points is minimal but not between source surface and target points. And that can be corrected by the reverse run at the same correcpondence distance. 

It is not as good as true symmetric ICP which optimizes  (see also feature request issue #4054, and link therein)

```
E(T) = sum_{(q,p) in K } [( ( q - T p) * n_q)^2 + (( T q - p ) * T n_q)]

```

**Comment by juandavid212** [comment]
I understand.
Thanks for your answer.
