### ISSUE TITLE
Conflict between open3D and Pytorch imports

### ISSUE THREAD

**Issue by erezposner** [isl-org/Open3D#5597]
I have this simple code below that multiplies two matrices.
```
import open3d as o3d
import torch

def f (a,b):
    return a @ b.T[:, :5]

cuda_device = 'cuda:0'
a = torch.eye(4, dtype=torch.float64).to(cuda_device)
b = torch.randn((100, 4), dtype=torch.float64).to(cuda_device)

print(f(a,b))
exit(0)
```

Running this code results with the following error when trying to run the line ```print(f(a,b))```:
```Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)```

To solve this,  all I need to do is to replace the imports order.
instead of:
```
import open3d as o3d
import torch
```

to to:
```
import torch
import open3d as o3d
```

And then the code runs, see output for example:
```
tensor([[-0.5093, -0.0432, -1.6252,  0.3523,  0.4462],
        [ 1.0926,  0.6892, -1.9338,  0.2381,  0.1581],
        [-0.1007, -0.3324,  2.4550,  0.7558, -0.2092],
        [-0.8802, -0.0881, -1.1041,  0.6719, -1.0906]], device='cuda:0',
       dtype=torch.float64)
```

My environment is as follows:
- Python version 3.7.13
- Open3D version '0.15.2'
- Pytorch version '1.11.0+cu113'
- CUDA Version: 11.7 

Can you please support this conflict?

**Comment by o0stinger0o** [comment]
I had a similar problem when reproducing point cloud related deep learning code. Since the python-pcl library is unmaintained for a long time, I chose to use open3D to calculate the normal vector. Similar to the method used by pcl I added the following function to my custom Dataset class:
`
    def get_normal(self, cld):
        import open3d as o3d
        cld = cld.astype(np.float32)
        cloud = o3d.geometry.PointCloud()
        cloud.points=o3d.utility.Vector3dVector(cld)
        cloud.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamKNN(knn=50))
        return np.asarray(cloud.normals,dtype=np.float32)
`
After that I use torch.utils.data.DataLoader to get the train_loader, and look at the relevant data, everything works fine.But when I try to load the model to the GPU with the data at the same time I get an unexpected error
`
model.to("cuda:0")
for i ,data in enumerate(train_loader):
    rgb, pcld, cld_rgb_nrm, choose, kp_targ_ofst, ctr_targ_ofst, \
    cls_ids, rts, labels, kp_3ds, ctr_3ds = data
    rgb = rgb.cuda()
`
`
Traceback (most recent call last):
  File "/home/lht/data/PVT3D/testtrain.py", line 115, in <module>
    rgb = rgb.cuda()
RuntimeError: CUDA error: unspecified launch failure
`
The strange thing is that I try to load one of the models or data individually, the error doesn't appear. And the code runs fine on cpu


If I move import open3d as o3d to the custom Dataset class header I get the following error

`
ERROR: Unexpected segmentation fault encountered in worker.
 Traceback (most recent call last):
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 24928) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lht/data/PVT3D/testtrain.py", line 112, in <module>
    for i ,data in enumerate(train_loader):
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1315, in _get_data
    success, data = self._try_get_data()
  File "/home/lht/anaconda3/envs/6d-pose/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 24928) exited unexpectedly

Process finished with exit code 1
`
My environment is as follows:

- Python version 3.7.13
- Open3D version '0.16.0'
- Pytorch version '1.12.1+cu116'
- CUDA Version: 11.6

**Comment by ssheorey** [comment]
Hi @erezposner, can you try with the latest release v0.16 and PyTorch v1.12 ? Running your script worked fine for me, no seg fault, with PyTorch 1.12.0+cu116 .

@o0stinger0o can you provide a minimal script to reproduce your error? It's best to open a new issue, since it may or may not be related to this one.

**Comment by DavidBrandes** [comment]
I am also having an issue with PyTorch and Open3d. For some reason when importing both packages running an inference task on a PyTorch model, the inference seems to get stuck somewhere without ever throwing an error, however also without ever finishing. After I out comment all imports for open3d, everything is working fine again.

Unfortunately I cannot provide a script to this issue as my code in which both packages get imported is quite big and interwoven. The PyTorch, CUDA and open3d versions I am using are 1.14.0.dev20221110, 11.7 and 0.16.1.

**Comment by erezposner** [comment]
@ssheorey Thanks it fixed it

**Comment by ssheorey** [comment]
@DavidBrandes your issue looks different from this one - please open a new issue. Also, we can't help without being able to reproduce it.
