### ISSUE TITLE
How to use webRTC to visualize animation from a remote headless server 

### ISSUE THREAD

**Issue by zhengqili** [isl-org/Open3D#5752]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I am trying to use webRTC to visualize a 3D reconstruction video from a remote headless server using "register_animation_callback" function, similar to the visualization used in https://github.com/cvg/nice-slam.  I followed the code from https://github.com/isl-org/Open3D/blob/master/examples/python/visualization/draw_webrtc.py to enable webrtc, and this code works perfectly fine. 

However, if I apply it to my visualization code with animation callback, I always get the error "GLFW Error: X11: The DISPLAY environment variable is missing". If I set DISPLAY to some value "xxxx"
, then it will raise another error "GLFW Error: X11: Failed to open display :xxxx". Any suggestion I can fix it to visualize such animation interactively from a remote server?

**Comment by ssheorey** [comment]
Hi @zhengqili see the example code here to create an interactive app with callbacks:
https://github.com/isl-org/Open3D/blob/master/examples/python/t_reconstruction_system/dense_slam_gui.py
You can run this over webRTC by enabling it as soon as you import open3d.visualization.

Since I don't see your animation callback code, I can only guess. I think it is likely the older GLFW based API - this does not support webRTC. You need to use the newer API (draw() or O3DVIsualizer() or open3d.visualization.gui...)

**Comment by zhengqili** [comment]
Thanks! What I am using for visualization is almost same as code from here: https://github.com/cvg/nice-slam/blob/master/src/tools/viz.py#L60

**Comment by ssheorey** [comment]
The code that you link to uses the older Open3D API - this does not support webRTC. Please switch to the new API (functions / classes from `o3d.visualization.{draw,gui,rendering}`) as in the example code I linked above.
