### ISSUE TITLE
Request to add (Autodesk Recap pro files)Rcp or Rcs support for Point cloud files

### ISSUE THREAD

**Issue by InquisitiveAS** [isl-org/Open3D#5939]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

I was wondering if someone has any ideas on this ?

**Comment by ssheorey** [comment]
Hi @InquisitiveAS does any software other than Autodesk support this file format? Is there a standard / format specification / reference implementation available? We cannot support proprietary file formats since their format is unknown and may change at any time.

I see that Autodesk Recap supports exporting to E57, which is a standard file format. We would welcome PRs for adding E57 support.
