### ISSUE TITLE
May I know how to render the points index from point cloud

### ISSUE THREAD

**Issue by Yanggeng001** [isl-org/Open3D#6254]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Dear Open3d developers:

I want to achieve the tasks as follows:

- [x] Render a raw point cloud (.ply file) to a series of 2D color and depth images by using offscreen rendering supported by open3d.
- [ ] I also want to know in each pixel of the rendered 2D image, what is the corresponding 3D point index, i.e. I want to know which point in 3D render to this pixel.

What I have tried so far:

- [x] For the first task, I can get the expected images by using Open3d visualizer offscreen rendering, set the cameras and render to images and depth images. 
- [ ] However, for this task, I check the source code in C++ repo but didn't find corresponding functions to do it. What I have tried is, I write the index of points in 3D as color channel to another dummy point cloud and render that dummy point cloud. But seems like my index datatype has been changed to unin8 and I cannot turn off the color grading functionality which will lead to modifying my index value but I want to keep it unchanged.

Really need some help here and really thanks for your time and support!!

**Comment by theNded** [comment]
This is non-trivial, as rasterization itself will by default blend points that are close to each other. Since this is not a feature we desire, we may not focus on developing it.
One potential option is to hack into the shaders and adapt your own renderer (upon several existing shaders). This functionality has been implemented in ElasticFusion. Some relevant code snippets can be found here:
- https://github.com/mp3guy/ElasticFusion/blob/master/Core/Shaders/index_map.vert
- https://github.com/mp3guy/ElasticFusion/blob/master/Core/IndexMap.cpp

Hope it helps! I will close the issue for now.
