### ISSUE TITLE
Minimal oriented bounding box is not minimal

### ISSUE THREAD

**Issue by belalhmedan90** [isl-org/Open3D#6866]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

I get non-minmal bounding box when calling `get_minimal_oriented_bounding_box` 

![minimal_obbox](https://github.com/user-attachments/assets/16453732-7b84-4ebb-850e-083eb8710e04)

### Steps to reproduce the bug

```python
import open3d as o3d

box_pcl = o3d.io.read_point_cloud(os.path.join(test_data_path, "pcl.ply"))

box_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(
    pcd=box_pcl, alpha=1.0
)

obbox = box_pcl.get_minimal_oriented_bounding_box(robust=True)
obbox.color = [0.5, 0.2, 0.7]

obbox2 = box_mesh.get_minimal_oriented_bounding_box(robust=True)
obbox2.color = [0.5, 0.7, 0.2]
## Visu
o3d.visualization.draw_geometries(
    [box_mesh, obbox, obbox2],
    window_name="minimal_obbox",
    point_show_normal=False,
    mesh_show_wireframe=False,
    mesh_show_back_face=False,
)
```

### Expected behavior

To get minimal Oriented Bounding Box

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.8
- Open3D version: 0.18.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): gcc 7.5
```

**Comment by nicolaloi** [comment]
I have reproduced the error, which is probably caused by [MeshBase::GetMinimalOrientedBoundingBox](https://github.com/isl-org/Open3D/blob/afb23f84e1e3fc09b049fe2016013becb684b7ad/cpp/open3d/geometry/MeshBase.cpp#L53-L55) having the same body as [MeshBase::GetOrientedBoundingBox](https://github.com/isl-org/Open3D/blob/afb23f84e1e3fc09b049fe2016013becb684b7ad/cpp/open3d/geometry/MeshBase.cpp#L49-L51), instead of being similar to [PointCloud::GetMinimalOrientedBoundingBox](https://github.com/isl-org/Open3D/blob/afb23f84e1e3fc09b049fe2016013becb684b7ad/cpp/open3d/geometry/PointCloud.cpp#L55-L58).

I'll open a PR.
