### ISSUE TITLE
Documentation: fix 'o3d.registration' in Tutorial/Advanced/Interactive_Visualization

### ISSUE THREAD

**Issue by DebbyX3** [isl-org/Open3D#6922]
Hello,

I was following this tutorial: [https://www.open3d.org/html/tutorial/Advanced/interactive_visualization.html](https://www.open3d.org/html/tutorial/Advanced/interactive_visualization.html)
and noticed that lines 62 and 70 (`p2p = o3d.registration.TransformationEstimationPointToPoint()`) would throw the following error:

`AttributeError: module 'open3d' has no attribute 'registration'`

I then found issue #2951 which suggested changing from:
`o3d.registration.[...]`
to
`o3d.pipelines.registration.[...]`
and this works.

Could you fix the tutorial page? Thanks!

**Comment by timohl** [comment]
Your link refers to an old version of the docs of version 0.9.0 (0.18.0 being the latest release).
Look in the bottom left corner, there should be a menu entry `Docs Version` where you can switch.

This should be the latest version (from the main dev branch):
[https://www.open3d.org/docs/latest/tutorial/visualization/interactive_visualization.html](https://www.open3d.org/docs/latest/tutorial/visualization/interactive_visualization.html)

This might be the fault of google, since when I google for `open3d tutorial` the top two results link to 0.9.0 and 0.7.0.
No idea how to fix this.

**Comment by DebbyX3** [comment]
Yes, you are right, that was one of the first Google results. Besides the version in the bottom left corner of the page, the URL doesn't suggest whether the page is referring to the latest or an older version of the docs (which I feel is usually how most docs URLs work)
Thanks! Please consider adding a banner :)

**Comment by DebbyX3** [comment]
(forgot to close)

**Comment by DebbyX3** [comment]
(forgot to close)
